name: binder_scoring_env
channels:
  - conda-forge
  - https://conda.graylab.jhu.edu
dependencies:
  - python=3.10
  - pandas>=2.1
  - biopython>=1.83
  - numpy<2.0
  - scipy
  - tqdm
  - pyrosetta
  - pip
  - pip:
      - dockq==2.1.3
      - parallelbar==2.5


